export default[
  { "_id": "A101", "title": "Propulsion Assignment", "course": "RS101", "description": "Analyze the fundamental principles of rocket propulsion and calculate thrust, specific impulse, and exhaust velocity for a given engine design.", "availableFrom": "May 6 at 12:00am", "due": "May 13 at 11:59pm", "points": 100, "modules": "Multiple Modules" },
  { "_id": "A102", "title": "Combustion Analysis", "course": "RS101", "description": "Perform a detailed combustion analysis of a bipropellant rocket engine, including stoichiometry, flame temperature, and combustion efficiency calculations.", "availableFrom": "May 13 at 12:00am", "due": "May 20 at 11:59pm", "points": 100, "modules": "Multiple Modules" },
  { "_id": "A103", "title": "Nozzle Design Project", "course": "RS101", "description": "Design and optimize a rocket nozzle using the method of characteristics. Submit CAD drawings and a report detailing your design choices and performance predictions.", "availableFrom": "May 20 at 12:00am", "due": "May 27 at 11:59pm", "points": 100, "modules": "Multiple Modules" },

  { "_id": "A201", "title": "Aerodynamics Quiz", "course": "RS102", "description": "Demonstrate understanding of subsonic and supersonic aerodynamic principles including lift, drag, and boundary layer theory as applied to aerospace vehicles.", "availableFrom": "May 6 at 12:00am", "due": "May 13 at 11:59pm", "points": 100, "modules": "Multiple Modules" },
  { "_id": "A202", "title": "Flow Analysis", "course": "RS102", "description": "Use computational fluid dynamics tools to analyze airflow over a given airfoil geometry. Submit simulation results and a written interpretation of flow behavior.", "availableFrom": "May 13 at 12:00am", "due": "May 20 at 11:59pm", "points": 100, "modules": "Multiple Modules" },
  { "_id": "A203", "title": "Heating Analysis", "course": "RS102", "description": "Evaluate aerodynamic heating effects on a re-entry vehicle traveling at hypersonic speeds. Analyze heat flux distribution and propose thermal protection strategies.", "availableFrom": "May 20 at 12:00am", "due": "May 27 at 11:59pm", "points": 100, "modules": "Multiple Modules" },

  { "_id": "A301", "title": "Structural Design Task", "course": "RS103", "description": "Design a load-bearing spacecraft structural component using appropriate materials and manufacturing techniques. Justify your material selection with stress and fatigue analysis.", "availableFrom": "May 6 at 12:00am", "due": "May 13 at 11:59pm", "points": 100, "modules": "Multiple Modules" },
  { "_id": "A302", "title": "Orbital Calculations", "course": "RS103", "description": "Compute orbital parameters for a spacecraft mission including transfer orbits, delta-v budgets, and launch windows using Kepler's laws and orbital mechanics equations.", "availableFrom": "May 13 at 12:00am", "due": "May 20 at 11:59pm", "points": 100, "modules": "Multiple Modules" },
  { "_id": "A303", "title": "Systems Engineering Exam", "course": "RS103", "description": "Demonstrate knowledge of spacecraft systems engineering processes including requirements definition, interface control, verification and validation, and risk management.", "availableFrom": "May 20 at 12:00am", "due": "May 27 at 11:59pm", "points": 100, "modules": "Multiple Modules" },

  { "_id": "A401", "title": "Molecular Structure Quiz", "course": "RS104", "description": "Identify and draw molecular structures for a set of organic compounds using IUPAC nomenclature. Predict bond angles and hybridization states for each molecule.", "availableFrom": "May 6 at 12:00am", "due": "May 13 at 11:59pm", "points": 100, "modules": "Multiple Modules" },
  { "_id": "A402", "title": "Reaction Mechanism Analysis", "course": "RS104", "description": "Propose step-by-step reaction mechanisms for a series of organic transformations. Identify nucleophiles, electrophiles, and intermediates in each reaction pathway.", "availableFrom": "May 13 at 12:00am", "due": "May 20 at 11:59pm", "points": 100, "modules": "Multiple Modules" },
  { "_id": "A403", "title": "Functional Group Synthesis Project", "course": "RS104", "description": "Design a multi-step synthetic route to a target organic molecule incorporating at least four distinct functional group transformations. Justify your reagent and condition choices.", "availableFrom": "May 20 at 12:00am", "due": "May 27 at 11:59pm", "points": 100, "modules": "Multiple Modules" },

  { "_id": "A501", "title": "Coordination Complex Problem Set", "course": "RS105", "description": "Solve problems involving coordination chemistry including naming complexes, determining oxidation states, predicting geometries, and applying crystal field theory.", "availableFrom": "May 6 at 12:00am", "due": "May 13 at 11:59pm", "points": 100, "modules": "Multiple Modules" },
  { "_id": "A502", "title": "Symmetry and Point Group Assignment", "course": "RS105", "description": "Assign point groups to a set of molecules and use character tables to determine IR and Raman active vibrational modes. Include symmetry element diagrams.", "availableFrom": "May 13 at 12:00am", "due": "May 20 at 11:59pm", "points": 100, "modules": "Multiple Modules" },
  { "_id": "A503", "title": "Solid State Structure Exam", "course": "RS105", "description": "Analyze crystal structures using X-ray diffraction data. Determine unit cell parameters, packing efficiency, and coordination environments for a given inorganic solid.", "availableFrom": "May 20 at 12:00am", "due": "May 27 at 11:59pm", "points": 100, "modules": "Multiple Modules" },

  { "_id": "A601", "title": "Thermodynamics Problem Set", "course": "RS106", "description": "Apply laws of thermodynamics to calculate enthalpy, entropy, and Gibbs free energy changes for a series of chemical reactions and phase transitions.", "availableFrom": "May 6 at 12:00am", "due": "May 13 at 11:59pm", "points": 100, "modules": "Multiple Modules" },
  { "_id": "A602", "title": "Spectroscopy Analysis", "course": "RS106", "description": "Interpret NMR, IR, and mass spectra to determine the structure of unknown compounds. Provide a complete structural elucidation with supporting evidence from each technique.", "availableFrom": "May 13 at 12:00am", "due": "May 20 at 11:59pm", "points": 100, "modules": "Multiple Modules" },
  { "_id": "A603", "title": "Kinetics Lab Report", "course": "RS106", "description": "Write a formal lab report analyzing the kinetics of a chemical reaction. Determine rate law, rate constant, and activation energy from experimental data using graphical methods.", "availableFrom": "May 20 at 12:00am", "due": "May 27 at 11:59pm", "points": 100, "modules": "Multiple Modules" },

  { "_id": "A701", "title": "Ancient Script Decipherment Exercise", "course": "RS107", "description": "Apply linguistic decipherment techniques to analyze a sample of an ancient Middle-earth script. Identify recurring patterns, propose phonetic values, and translate a short passage.", "availableFrom": "May 6 at 12:00am", "due": "May 13 at 11:59pm", "points": 100, "modules": "Multiple Modules" },
  { "_id": "A702", "title": "Language Evolution Essay", "course": "RS107", "description": "Write a scholarly essay tracing the evolution of a Middle-earth language family over time. Discuss phonological shifts, borrowed vocabulary, and the influence of historical events on linguistic change.", "availableFrom": "May 13 at 12:00am", "due": "May 20 at 11:59pm", "points": 100, "modules": "Multiple Modules" },
  { "_id": "A703", "title": "Manuscript Translation Project", "course": "RS107", "description": "Translate a provided excerpt from an ancient Middle-earth manuscript into modern English. Include annotations explaining your translation choices and any ambiguous passages.", "availableFrom": "May 20 at 12:00am", "due": "May 27 at 11:59pm", "points": 100, "modules": "Multiple Modules" },

  { "_id": "A801", "title": "Spellcasting Theory Exam", "course": "RS108", "description": "Demonstrate theoretical knowledge of spellcasting mechanics including incantation structure, magical energy channeling, and the ethical use of spells in various scenarios.", "availableFrom": "May 6 at 12:00am", "due": "May 13 at 11:59pm", "points": 100, "modules": "Multiple Modules" },
  { "_id": "A802", "title": "Elven Lore Research Paper", "course": "RS108", "description": "Research and write an academic paper on a chosen aspect of Elven lore, drawing from primary texts and scholarly commentary. Cite all sources using proper academic formatting.", "availableFrom": "May 13 at 12:00am", "due": "May 20 at 11:59pm", "points": 100, "modules": "Multiple Modules" },
  { "_id": "A803", "title": "Potion Crafting Practical", "course": "RS108", "description": "Document the step-by-step process of crafting a chosen potion, including ingredient sourcing, preparation techniques, and safety precautions. Submit a lab report with your results and observations.", "availableFrom": "May 20 at 12:00am", "due": "May 27 at 11:59pm", "points": 100, "modules": "Multiple Modules" }
]